/** @format */

import { Box, Button, Flex, Heading } from '@chakra-ui/react';
import { useState } from 'react';
import { useRouter } from 'next/router';
import Head from 'next/head';

const CaptchaPage = () => {
	const router = useRouter();
	const [isVerified, setIsVerified] = useState(false);

	const handleVerification = () => {
		// Implement your captcha verification logic here
		// If the verification is successful, set `isVerified` to `true`
		setIsVerified(true);
	};

	const handleProceed = () => {
		router.push('/payment');
	};

	return (
		<>
			<Head>
				<title>Bhujal Sarvekshan Kendra</title>
				<meta name='description' content='Generated by Shivanshu Pathak' />
				<link rel='icon' href='/Earth.ico' />
			</Head>
			<Box p={4}>
				<Heading as='h1' mb={6}>
					Captcha Verification
				</Heading>
				<Flex justifyContent='center'>
					<Box maxW='lg' borderWidth='1px' borderRadius='lg' p={8}>
						{isVerified ? (
							<>
								<Heading as='h2' mb={6}>
									Verification Successful!
								</Heading>
								<Button onClick={handleProceed} colorScheme='blue' width='full'>
									Proceed to Payment
								</Button>
							</>
						) : (
							<Button
								onClick={handleVerification}
								colorScheme='blue'
								width='full'>
								Verify
							</Button>
						)}
					</Box>
				</Flex>
			</Box>
		</>
	);
};

export default CaptchaPage;
