/* @format */

import { type NextPage } from 'next';
import Head from 'next/head';
import {
	Box,
	Heading,
	Text,
	Button,
	Stack,
	CardBody,
	ButtonGroup,
	Card,
	CardFooter,
	Divider,
	SimpleGrid,
	Image,
	Center,
} from '@chakra-ui/react';
import Navbar from '~/Navbar/Navbar';
import Footer from '~/Footer/Footer';
import { useEffect } from 'react';
import { useUser } from '@clerk/clerk-react';
import { useRouter } from 'next/router';

const DashboardPage = () => {
	const { isSignedIn } = useUser();
	const router = useRouter();
	if (!isSignedIn) {
		// Redirect to the login page if the user is not signed in
		router.push('/login');
		return null;
	}
	return (
		<>
			<Navbar />
			<Head>
				<title>Bhujal Sarvekshan Kendra</title>
				<meta name='description' content='Generated by Shivanshu Pathak' />
				<link rel='icon' href='/Earth.ico' />
			</Head>
			<Box
				w='100%'
				h='220px'
				bgGradient={[
					'linear(to-tr, green.300, yellow.400)',
					'linear(to-t, red.200, teal.500)',
					'linear(to-b, blue.100, purple.300)',
				]}>
				<center>
					<br />
					<Text
						bgGradient='linear(to-l, #7928CA, #FF0080)'
						bgClip='text'
						fontSize='4xl'
						fontWeight='extrabold'>
						मध्य प्रदेश शासन
					</Text>
					<Text
						bgGradient='linear(to-l, #7928CA, #FF0080)'
						bgClip='text'
						fontSize='5xl'
						fontWeight='extrabold'>
						भू-जल सर्वेक्षण केन्द्र
					</Text>
				</center>
			</Box>
			<br />
			<center>
				<Box maxW='32rem'>
					<Heading mb={2}>भू-जल सर्वेक्षण</Heading>
					<br />
					<Text fontSize='lg'>
						भू-जल सर्वेक्षण केन्द्र, गली नंबर 3, सिद्धार्थ नगर, सतना, मध्य
						प्रदेश 485001
					</Text>
					<Text fontSize='lg'>संचालक : +91 9753259259 / +91 9425180023</Text>
					<Text fontSize='lg'>ई-मेल: bhujalsarvkeshankendra@gmail.com</Text>
					<Stack
						flex={{ base: 2, md: 0 }}
						justify={'flex-end'}
						direction={'column'}
						spacing={6}></Stack>
				</Box>
			</center>
			<br />
			<br />
			<br />
			<Box>
				<Heading>
					<center>Reviews</center>
				</Heading>
			</Box>
			<br />
			<br />
			<Stack
				flex={{ base: 2, md: 5 }}
				justify={'flex-center'}
				direction={'row'}
				spacing={3}>
				<Card maxW='lg'>
					<CardBody>
						<Center>
							<Image
								borderRadius='full'
								boxSize='250px'
								src='https://bit.ly/dan-abramov'
								alt='Dan Abramov'
							/>
						</Center>
						<Stack mt='6' spacing='4'>
							<Heading size='md'>Living room Sofa</Heading>
							<Text>
								This sofa is perfect for modern tropical spaces, baroque
								inspired spaces, earthy toned spaces and for people who love a
								chic design with a sprinkle of vintage design.
							</Text>
							<Text color='blue.600' fontSize='2xl'>
								$450
							</Text>
						</Stack>
					</CardBody>
					<Divider />
				</Card>
				<Card maxW='lg'>
					<CardBody>
						<Center>
							<Image
								borderRadius='full'
								boxSize='250px'
								src='https://bit.ly/dan-abramov'
								alt='Dan Abramov'
							/>
						</Center>
						<Stack mt='6' spacing='4'>
							<Heading size='md'>Living room Sofa</Heading>
							<Text>
								This sofa is perfect for modern tropical spaces, baroque
								inspired spaces, earthy toned spaces and for people who love a
								chic design with a sprinkle of vintage design.
							</Text>
							<Text color='blue.600' fontSize='2xl'>
								$450
							</Text>
						</Stack>
					</CardBody>
					<Divider />
				</Card>
				<Card maxW='lg'>
					<CardBody>
						<Center>
							<Image
								borderRadius='full'
								boxSize='250px'
								src='https://bit.ly/dan-abramov'
								alt='Dan Abramov'
							/>
						</Center>
						<Stack mt='6' spacing='4'>
							<Heading size='md'>Living room Sofa</Heading>
							<Text>
								This sofa is perfect for modern tropical spaces, baroque
								inspired spaces, earthy toned spaces and for people who love a
								chic design with a sprinkle of vintage design.
							</Text>
							<Text color='blue.600' fontSize='2xl'>
								$450
							</Text>
						</Stack>
					</CardBody>
					<Divider />
				</Card>
			</Stack>
			<br />
			<Stack
				flex={{ base: 2, md: 5 }}
				justify={'flex-center'}
				direction={'row'}
				spacing={3}>
				<Card maxW='lg'>
					<CardBody>
						<Center>
							<Image
								borderRadius='full'
								boxSize='250px'
								src='https://bit.ly/dan-abramov'
								alt='Dan Abramov'
							/>
						</Center>
						<Stack mt='6' spacing='4'>
							<Heading size='md'>Living room Sofa</Heading>
							<Text>
								This sofa is perfect for modern tropical spaces, baroque
								inspired spaces, earthy toned spaces and for people who love a
								chic design with a sprinkle of vintage design.
							</Text>
							<Text color='blue.600' fontSize='2xl'>
								$450
							</Text>
						</Stack>
					</CardBody>
					<Divider />
				</Card>
				<Card maxW='lg'>
					<CardBody>
						<Center>
							<Image
								borderRadius='full'
								boxSize='250px'
								src='https://bit.ly/dan-abramov'
								alt='Dan Abramov'
							/>
						</Center>
						<Stack mt='6' spacing='4'>
							<Heading size='md'>Living room Sofa</Heading>
							<Text>
								This sofa is perfect for modern tropical spaces, baroque
								inspired spaces, earthy toned spaces and for people who love a
								chic design with a sprinkle of vintage design.
							</Text>
							<Text color='blue.600' fontSize='2xl'>
								$450
							</Text>
						</Stack>
					</CardBody>
					<Divider />
				</Card>
				<Card maxW='lg'>
					<CardBody>
						<Center>
							<Image
								borderRadius='full'
								boxSize='250px'
								src='https://bit.ly/dan-abramov'
								alt='Dan Abramov'
							/>
						</Center>
						<Stack mt='6' spacing='4'>
							<Heading size='md'>Living room Sofa</Heading>
							<Text>
								This sofa is perfect for modern tropical spaces, baroque
								inspired spaces, earthy toned spaces and for people who love a
								chic design with a sprinkle of vintage design.
							</Text>
							<Text color='blue.600' fontSize='2xl'>
								$450
							</Text>
						</Stack>
					</CardBody>
					<Divider />
				</Card>
			</Stack>

			<br />
			<Footer />
		</>
	);
};

export default DashboardPage;
