/* @format */

import { type NextPage } from 'next';
import Head from 'next/head';
import { Box, Heading } from '@chakra-ui/react';
// `@chakra-ui/theme` is a part of the base install with `@chakra-ui/react`
import chakraTheme from '@chakra-ui/theme';

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Bhujal Sarvekshan Kendra</title>
				<meta name='description' content='Generated by create-t3-app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Box w='100%' h='200px' bgGradient='linear(to-r, green.200, pink.500)'>
				<Heading as='h2' size='3xl' noOfLines={1}>
					Bhujal <span>Sarvekshan</span> Kendra
				</Heading>
			</Box>
		</>
	);
};

export default Home;
