/* @format */

import { type NextPage } from 'next';
import Head from 'next/head';
import { Box, Heading, Text, Button, Stack } from '@chakra-ui/react';
// `@chakra-ui/theme` is a part of the base install with `@chakra-ui/react`
import Navbar from '~/Navbar/Navbar';
import Footer from '~/Footer/Footer';

const Home: NextPage = () => {
	return (
		<>
			<Navbar />
			<Head>
				<title>Bhujal Sarvekshan Kendra</title>
				<meta name='description' content='Generated by Shivanshu Pathak' />
				<link rel='icon' href='/Earth.ico' />
			</Head>
			<Box
				w='100%'
				h='200px'
				bgGradient={[
					'linear(to-tr, teal.300, yellow.400)',
					'linear(to-t, blue.200, teal.500)',
					'linear(to-b, orange.100, purple.300)',
				]}>
				<center>
					<br />
					<Text
						bgGradient='linear(to-l, #7928CA, #FF0080)'
						bgClip='text'
						fontSize='4xl'
						fontWeight='extrabold'>
						मध्य प्रदेश शासन
					</Text>
					<Text
						bgGradient='linear(to-l, #7928CA, #FF0080)'
						bgClip='text'
						fontSize='5xl'
						fontWeight='extrabold'>
						भू-जल सर्वेक्षण केन्द्र
					</Text>
				</center>
			</Box>
			<br />
			<center>
				<Box maxW='32rem'>
					<Heading mb={2}>भू-जल सर्वेक्षण</Heading>
					<br />
					<Text fontSize='lg'>
						भू-जल सर्वेक्षण केन्द्र, गली नंबर 3, सिद्धार्थ नगर, सतना, मध्य
						प्रदेश 485001
					</Text>
					<Text fontSize='lg'>संचालक : +91 9753259259 / +91 9425180023</Text>
					<Text fontSize='lg'>ई-मेल: bhujalsarvkeshankendra@gmail.com</Text>
					<Stack
						flex={{ base: 2, md: 0 }}
						justify={'flex-end'}
						direction={'column'}
						spacing={6}>
						<Button
							size='lg'
							colorScheme='green'
							mt='24px'
							as={'a'}
							href='./SignIn.tsx'>
							Sign In
						</Button>
						<Button
							size='lg'
							colorScheme='red'
							mt='24px'
							as={'a'}
							href='./SignUp.tsx'>
							Sign Up
						</Button>
					</Stack>
				</Box>
			</center>
			<br />
			<Footer />
		</>
	);
};

export default Home;
