/** @format */

import React, { useEffect } from 'react';
import { loadStripe } from '@stripe/stripe-js';
import { Center, Heading, Button, Link } from '@chakra-ui/react';
import Head from 'next/head';

const Payment = () => {
	useEffect(() => {
		const loadStripeScript = async () => {
			const stripe = await loadStripe(
				'pk_test_51N0WiKSC5wWa4gvr1l8w6upWePBczZLG0jFqOAyUt6ss70TjGmoVb5KytBzN17ECfqR3s5ZqKUqSTWtCqbAMqbok00JgSGkDZU'
			);
			// You can now use the `stripe` object to initialize the payment flow
		};

		loadStripeScript();
	}, []);

	return (
		<div>
			<Head>
				<title>Bhujal Sarvekshan Kendra</title>
				<meta name='description' content='Generated by Shivanshu Pathak' />
				<link rel='icon' href='/Earth.ico' />
			</Head>
			<Center>
				<Heading>Payment Page</Heading>
			</Center>
			<Center>
				<br />
				<br />
				<br />
				<br />
				<br />
				<Link href='https://buy.stripe.com/test_7sI6oMb9Z3zF1c4dQQ'>
					<Button>Proceed To Payment</Button>
				</Link>
			</Center>
		</div>
	);
};

export default Payment;
